#!/usr/bin/python3
import tkinter as tk
from tkinter import filedialog
import os
root = tk.Tk()
root.withdraw()
print('请选择mav0所在文件夹')
Folderpathcam0 = filedialog.askdirectory()


command = './Examples/Monocular-Inertial/mono_inertial_euroc ./Vocabulary/ORBvoc.txt ./Examples/Monocular-Inertial/airsim.yaml ' + Folderpathcam0 + ' ./Examples/Monocular-Inertial/EuRoC_TimeStamps/traj1.txt traj1_monoi'
print(command)
os.system(command)
